spring.application.name=paymentService
logging.level.com.example.paymentservice=DEBUG

# -------------------------------
# Environment Variables
# -------------------------------

payment.expiry.duration=10
payment.expiry.unit=MINUTES

# -------------------------------
# MongoDB Connection Configuration
# -------------------------------

spring.data.mongodb.uri=mongodb://127.0.0.1:27017/paymentTransactions
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG



