spring.application.name=PaymentService

# -------------------------------
# MongoDB Connection Configuration
# -------------------------------
#spring.data.mongodb.uri=mongodb://localhost:27017/paymentService


logging.level.com.example.payment=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

