spring.application.name=paymentService
logging.level.com.example.paymentservice=DEBUG
server.port=8082

# -------------------------------
# Environment Variables
# -------------------------------

payment.expiry.duration=2
payment.expiry.unit=MINUTES
card.mask=**** **** ****

# -------------------------------
# MongoDB Connection Configuration
# -------------------------------
spring.data.mongodb.uri=mongodb://localhost:27017/paymentService


logging.level.com.example.payment=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

